version: '3'

services:
  apache:
    # image: 'php:8.1.19-apache'
    # Criar o arquivo Dockerfile
    build: . 
    container_name: php
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./html:/var/www/html